name: CD Firebase
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['16']
    name: Node ${{ matrix.node }} CD Firebase
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
      - run: npm run build
      - run: npm ci
        working-directory: ./functions
      - run: npm run build
        working-directory: ./functions
      - run: npx firebase deploy  --project=default --token=${{ secrets.FIREBASE_TOKEN }}
